version: '3'
services:
  nodeapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
  redisdb:
    build:
      context: .
      dockerfile: Dockerfile.redis
    restart: always
    ports:
      - 6379:6379
