apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-server-deployment
spec:
  selector:
    matchLabels:
      component: node-server
  template:
    metadata:
      labels:
        component: node-server
    spec:
      containers:
      - name: node-server-deployment
        image: porwalamit/devopsadvanced:4
        ports:
        - containerPort: 8086
        env:
          - name: REDIS_HOST
            value: redis-clusterip-service
          - name: REDIS_PORT
            value: '6379'
